### PR TITLE
Fixes/signup redirect copytextfield

### LINKED ISSUE #92: Component: Profile
Profile component/view in dashboard

### LINKED ISSUE #132: View: Redirect from login/signup

### LINKED ISSUE #133: Login/Signup link

### LINKED ISSUE #134: Component: Update Header (isAuthenticated)

### LINKED ISSUE #137: Bug: CopyTextField doesn't work
Can't read "select()" of undefined.

the noderef is being passed to the container rather than the input

### PR DESCRIPTION
**Pull request by Ciavarella**
Removed a-tag and replaced it with react link. Link on Login & Sign up now works.
closes #133 

Added redirect when logged in to path: /dashboard.
Added redirect from signup to path: /login after the user is created.
closes #132 

Fixed bug on CopyTextfield. This now works but maybe needs a notification that the input value is copied to clipboard.
closes #137 

Updated component Header to check if user is logged in and replaces log/signup buttons with button to path: /dashboard on landingpage.
closes #134 

closes #92

### CODE REVIEW

**Review by lessp — APPROVED** [review]

File: src/redux/signup/signupReducer.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ const signupReducer = (state = initialState, action) => {
         ...state,
         user: action.payload.user,
         isFetching: false,
-        message: action.payload.message
+        message: action.payload.success
```
Comment (lessp) [inline src/redux/signup/signupReducer.js]: Switch to message instead, the boolean is probably not something that is helpful to show for the user on success!

Comment (Ciavarella) [reply src/redux/signup/signupReducer.js]: Agree, fixed it with my latest commit.

**Review by joakimunge — APPROVED** [review]
Might want to move signup actions into a userReducer or similar. But we can work with this for now!
